## Обработка данных

In [1]:
import pandas as pd
df = pd.read_csv('data/users_behavior.csv')

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3214 entries, 0 to 3213
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   calls     3214 non-null   float64
 1   minutes   3214 non-null   float64
 2   messages  3214 non-null   float64
 3   mb_used   3214 non-null   float64
 4   is_ultra  3214 non-null   int64
dtypes: float64(4), int64(1)
memory usage: 125.7 KB

In [4]:
df.describe()

             calls      minutes     messages       mb_used     is_ultra
count  3214.000000  3214.000000  3214.000000   3214.000000  3214.000000
mean     63.038892   438.208787    38.281269  17207.673836     0.306472
std      33.236368   234.569872    36.148326   7570.968246     0.461100
min       0.000000     0.000000     0.000000      0.000000     0.000000
25%      40.000000   274.575000     9.000000  12491.902500     0.000000
50%      62.000000   430.600000    30.000000  16943.235000     0.000000
75%      82.000000   571.927500    57.000000  21424.700000     1.000000
max     244.000000  1632.060000   224.000000  49745.730000     1.000000

In [5]:
df['is_ultra'].value_counts(normalize=True)

is_ultra
0    0.693528
1    0.306472
Name: proportion, dtype: float64

In [6]:
df_train, df_valid = train_test_split(df, test_size = 0.2, random_state =12345, stratify = df['is_ultra'])

In [7]:
df_train, df_test  = train_test_split(df_train, test_size = 0.25, random_state = 12345, stratify =  df_train['is_ultra'])

In [8]:
df_train.shape

(1928, 5)

In [9]:
df_test.shape

(643, 5)

In [10]:
df_valid.shape

(643, 5)

In [11]:
features = df_train.drop('is_ultra', axis = 1)
target = df_train['is_ultra']

In [12]:
features_valid = df_valid.drop('is_ultra', axis = 1)
target_valid = df_valid['is_ultra']

In [13]:
from sklearn.dummy import DummyClassifier
dummy = DummyClassifier(strategy='most_frequent').fit(features, target)
baseline = accuracy_score(target_valid, dummy.predict(features_valid))
baseline

0.6936236391912908

Перекос 69/31 означает, что accuracy сама по себе неинформативна и любую модель надо сравнивать с константой 0,694

## Тест Моделей

### Деревья

In [14]:
from sklearn.tree import DecisionTreeClassifier

In [15]:
best_depth = 0
best_result  = 0
for depth in range(1, 11):
    tree = DecisionTreeClassifier(random_state=12345, max_depth=depth) 
    tree.fit(features, target) 
    predictions = tree.predict(features_valid) 
    result = accuracy_score(target_valid, predictions) 
    if result > best_result:
        best_depth = depth
        best_result = result
         
    print(f"max_depth: {depth}, accuracy: {result}")
print()
print(f"best_depth: {best_depth}, accuracy: {best_result}")

max_depth: 1, accuracy: 0.7480559875583204
max_depth: 2, accuracy: 0.7853810264385692
max_depth: 3, accuracy: 0.7993779160186625
max_depth: 4, accuracy: 0.7838258164852255
max_depth: 5, accuracy: 0.7962674961119751
max_depth: 6, accuracy: 0.7978227060653188
max_depth: 7, accuracy: 0.7822706065318819
max_depth: 8, accuracy: 0.7791601866251944
max_depth: 9, accuracy: 0.7822706065318819
max_depth: 10, accuracy: 0.7822706065318819

best_depth: 3, accuracy: 0.7993779160186625

### Леса

In [16]:
from sklearn.ensemble import RandomForestClassifier

In [17]:
best_n = 0
best_resualt_2 = 0
best_depth_2 = 0
for n in [10, 20, 30, 40, 50]:
    for depth_2 in range(1, 11):
        forest = RandomForestClassifier(random_state=12345, n_estimators=n, max_depth=depth_2) 
        forest.fit(features, target) 
        predictions_valid_forest = forest.predict(features_valid) 
        result_2 =  accuracy_score(target_valid, predictions_valid_forest)
        if result_2 > best_resualt_2:
            best_resualt_2 = result_2
            best_n = n
            best_depth_2 = depth_2
            best_resualt_2 = result_2
        print(f"depth: {depth_2}, n: {n}, accuracy: {result_2}")   
print(f"best_depth: {best_depth_2}")
print(f"best_n: {best_n}")    
print(f"best_resualt: {best_resualt_2}")

depth: 1, n: 10, accuracy: 0.7511664074650077
depth: 2, n: 10, accuracy: 0.7667185069984448

depth: 3, n: 10, accuracy: 0.7822706065318819
depth: 4, n: 10, accuracy: 0.7900466562986003
depth: 5, n: 10, accuracy: 0.807153965785381
depth: 6, n: 10, accuracy: 0.8055987558320373
depth: 7, n: 10, accuracy: 0.8102643856920684

depth: 8, n: 10, accuracy: 0.8102643856920684
depth: 9, n: 10, accuracy: 0.8087091757387247

depth: 10, n: 10, accuracy: 0.7978227060653188
depth: 1, n: 20, accuracy: 0.744945567651633
depth: 2, n: 20, accuracy: 0.7838258164852255
depth: 3, n: 20, accuracy: 0.7993779160186625

depth: 4, n: 20, accuracy: 0.7947122861586314
depth: 5, n: 20, accuracy: 0.807153965785381

depth: 6, n: 20, accuracy: 0.8133748055987559
depth: 7, n: 20, accuracy: 0.8087091757387247
depth: 8, n: 20, accuracy: 0.8118195956454122

depth: 9, n: 20, accuracy: 0.8133748055987559
depth: 10, n: 20, accuracy: 0.8164852255054432

depth: 1, n: 30, accuracy: 0.744945567651633
depth: 2, n: 30, accuracy: 0.7822706065318819
depth: 3, n: 30, accuracy: 0.7993779160186625

depth: 4, n: 30, accuracy: 0.7993779160186625

depth: 5, n: 30, accuracy: 0.8087091757387247
depth: 6, n: 30, accuracy: 0.8195956454121306
depth: 7, n: 30, accuracy: 0.8164852255054432

depth: 8, n: 30, accuracy: 0.8164852255054432

depth: 9, n: 30, accuracy: 0.8164852255054432
depth: 10, n: 30, accuracy: 0.8164852255054432

depth: 1, n: 40, accuracy: 0.744945567651633

depth: 2, n: 40, accuracy: 0.7853810264385692
depth: 3, n: 40, accuracy: 0.7978227060653188
depth: 4, n: 40, accuracy: 0.7993779160186625

depth: 5, n: 40, accuracy: 0.8040435458786936

depth: 6, n: 40, accuracy: 0.8149300155520995
depth: 7, n: 40, accuracy: 0.8164852255054432

depth: 8, n: 40, accuracy: 0.8195956454121306

depth: 9, n: 40, accuracy: 0.8164852255054432
depth: 10, n: 40, accuracy: 0.8164852255054432

depth: 1, n: 50, accuracy: 0.7729393468118196

depth: 2, n: 50, accuracy: 0.7838258164852255
depth: 3, n: 50, accuracy: 0.7978227060653188

depth: 4, n: 50, accuracy: 0.8009331259720062

depth: 5, n: 50, accuracy: 0.80248833592535

depth: 6, n: 50, accuracy: 0.8180404354587869

depth: 7, n: 50, accuracy: 0.8180404354587869

depth: 8, n: 50, accuracy: 0.8164852255054432

depth: 9, n: 50, accuracy: 0.8195956454121306

depth: 10, n: 50, accuracy: 0.8180404354587869
best_depth: 6
best_n: 30
best_resualt: 0.8195956454121306

In [18]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(random_state=12345, solver='lbfgs', max_iter=1000) 
model.fit(features, target)

LogisticRegression(max_iter=1000, random_state=12345)

In [19]:
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
pipe = make_pipeline(StandardScaler(), LogisticRegression(random_state=12345))

In [20]:
pipe.fit(features, target)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('logisticregression', LogisticRegression(random_state=12345))])

In [21]:
predictions_pipe = pipe.predict(features_valid)
accuracy_pipe = accuracy_score(target_valid, predictions_pipe)

predictions_logistic = model.predict(features_valid)
accuracy_logistic = accuracy_score(target_valid, predictions_logistic)

print(f'accuracy_pipe: {accuracy_pipe}')
print(f'accuracy_logistic: {accuracy_logistic}')

accuracy_pipe: 0.7371695178849145
accuracy_logistic: 0.7371695178849145

 Несколько конфигураций дали неразличимый результат и выбрана самая экономная.
 Более точной моделью оказался случайный лес с глубиной 6 и 30 деревьями

In [22]:
print(f'доля предсказанных «Ультра» на валидации: { predictions_pipe.mean()}')

доля предсказанных «Ультра» на валидации: 0.06531881804043546

In [23]:
print(f'реальная доля «Ультра» на валидации  : { target_valid.mean()}')

реальная доля «Ультра» на валидации  : 0.30637636080870917

In [24]:
baseline

0.6936236391912908

In [25]:
data = [['best_depth: 3', 0.7993779160186625, 0.7993779160186625-baseline], 
    ['best_depth: 6, best_n: 30', 0.8195956454121306, 0.8195956454121306-baseline],
    ['max_iter=1000', 0.7371695178849145, 0.7371695178849145-baseline]]

sverka = pd.DataFrame(data, columns=['гиперпараметры', 'accuracy на валидации', 'над базовым уровнем'], index = ['tree', 'forest', 'logistic'])
sverka

,гиперпараметры,accuracy на валидации,над базовым уровнем
tree,best_depth: 3,0.799378,0.105754
forest,"best_depth: 6, best_n: 30",0.819596,0.125972
logistic,max_iter=1000,0.737170,0.043546

Лучшей моделью стал случайный лес с параметрами best_depth: 6, best_n: 30, обходит константу на 0.125972. логистическая регрессия провалилась потому что она пошла по простому пути и просто начала относить к максимальному классу. Она не ищет скрытых зависимостей.

## Переобучение и проверка лучшей модели

In [26]:
new_data = pd.concat([df_train, df_valid])
new_features = new_data.drop('is_ultra', axis = 1)
new_target =   new_data['is_ultra']

In [27]:
features_test = df_test.drop('is_ultra', axis = 1)
target_test = df_test['is_ultra']

In [28]:
dummy_2 = DummyClassifier(strategy='most_frequent').fit(new_features, new_target)
baseline_2 = accuracy_score(target_test, dummy_2.predict(features_test))
baseline_2

0.6936236391912908

In [29]:
best_forest =  RandomForestClassifier(random_state=12345, n_estimators=30, max_depth=6)

In [30]:
best_forest.fit(new_features, new_target)

RandomForestClassifier(max_depth=6, n_estimators=30, random_state=12345)

In [31]:
predictions_test = best_forest.predict(features_test)

In [32]:
best_accuracy_2 = accuracy_score(target_test, predictions_test)

In [33]:
best_accuracy_2

0.8180404354587869

In [34]:
best_accuracy_2 - baseline_2

0.12441679626749613

Модель прошла порог в 0,75
Обходит константу на 12 процентных пункта
Чуть-чуть разошлась с валидационной оценкой но в шум заходит

## Дополнительные метрики логистической регрессии

Accuracy не показывает, что модель почти не находит редкий класс. Считаем recall и precision по «Ультра».

In [35]:
from sklearn.metrics import recall_score, precision_score
print('recall по «Ультра»:', recall_score(target_valid, predictions_pipe))
print('precision по «Ультра»:', precision_score(target_valid, predictions_pipe))
print('нашёл Ультра:', ((predictions_pipe==1) & (target_valid==1)).sum(), 'из', target_valid.sum())

recall по «Ультра»: 0.17766497461928935

precision по «Ультра»: 0.8333333333333334
нашёл Ультра: 35 из 197

## Общий вывод

**Задача.** Оператор «Мегалайн» хочет автоматически предлагать клиентам
с архивных тарифов один из двух актуальных — «Смарт» или «Ультра».
В распоряжении было поведение 3214 клиентов за месяц: количество звонков,
суммарные минуты, число сообщений и израсходованный трафик. Нужна модель
классификации с долей правильных ответов не ниже 0,75.

**Как проверялось качество.** Данные разделены на три части в пропорции
60/20/20 со стратификацией по целевому признаку. Гиперпараметры всех моделей
подбирались на валидационной выборке; тестовая выборка не использовалась
до самого конца и была задействована ровно один раз — для замера итоговой
модели. Финальная модель переобучена на обучающей и валидационной выборках
вместе.

**Точка отсчёта.** Классы распределены неравномерно: 69% клиентов на «Смарт»,
31% на «Ультра». Поэтому доля правильных ответов сама по себе неинформативна:
модель, которая всем без разбора советует «Смарт», получает 0,694, не
анализируя ничего. Все результаты ниже сравниваются именно с этим уровнем.

**Результат.** Лучшей оказалась модель случайного леса — 30 деревьев,
максимальная глубина 6. На тестовой выборке она даёт **0,818** против **0,694**
у константного правила, то есть выигрывает **12,4 процентных пункта**.
В переводе на клиентов: из каждых 100 верную рекомендацию получат около 82
против 69 при простейшем правиле — примерно 13 дополнительных клиентов
на каждую сотню. Порог 0,75 пройден с запасом.

Расхождение с валидационной оценкой (0,820) составило 0,2 процентных пункта
при стандартной ошибке около 1,6 — то есть результат воспроизвёлся.

**Сравнение моделей.**

| модель | accuracy на валидации | над константой |
|---|---:|---:|
| случайный лес (30 деревьев, глубина 6) | 0,820 | +12,6 |
| решающее дерево (глубина 3) | 0,799 | +10,6 |
| логистическая регрессия | 0,737 | +4,4 |

Логистическая регрессия фактически провалилась, и это стоит объяснить.
Она отнесла к «Ультра» лишь 6,5% клиентов при реальной доле 31%: из 197
пользователей «Ультра» в валидационной выборке она нашла 35. При этом
из тех, кого она всё же назвала «Ультра», права она в 83% случаев. То есть
модель научилась узнавать только самые очевидные случаи — клиентов
с экстремально высоким трафиком и разговором, — а всех остальных на всякий
случай относит к большинству. Её accuracy 0,737 выглядит приемлемо ровно
потому, что «относить всех к большинству» на таких данных и есть выигрышная
стратегия по этой метрике.

Причина в устройстве модели: логистическая регрессия проводит одну прямую
границу между классами, а «Ультра» и «Смарт» в этих четырёх признаках так
не разделяются. Дерево и лес строят границу из множества условий и потому
улавливают сочетания признаков, недоступные линейной модели.

Несколько конфигураций леса дали статистически неразличимый результат
(разброс в пределах 0,3 п.п. при стандартной ошибке 1,6 п.п.) — из них
выбрана самая экономная по вычислениям.

**Ограничения.**

1. Accuracy не различает типы ошибок. Предложить «Смарт» тому, кому нужен
   «Ультра», и наоборот — разные потери для оператора, а метрика считает их
   одинаковыми. Прежде чем внедрять, стоит договориться с заказчиком о цене
   каждой из двух ошибок и перейти на метрику, которая её учитывает.
2. Признаков всего четыре, и они сильно связаны между собой: звонки и минуты
   описывают почти одно и то же. Потолок качества на таких данных невысок.
3. Различия между близкими конфигурациями лежат в пределах шума — выбор
   «лучшей» модели с точностью до третьего знака здесь не имеет смысла.

**Что дальше.** Главное, чего не хватает для практической пользы, — цены
тарифов и суммы, которую клиент фактически платит. Модель сейчас угадывает,
каким тарифом клиент пользуется, а бизнес-вопрос другой: какой тариф ему
выгоднее предложить. Это разные задачи, и вторая требует данных о деньгах,
а не только о поведении.